version: '3.8'

services:
  fastapi-app:
    build: ./microservice
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - ollama
      - chromadb
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CHROMA_DB_PATH=/chroma_db
      - OLLAMA_HOST=http://ollama:11434
    volumes:
      - chroma_db:/chroma_db
    networks:
      - ollama_network  # Ensure both services are on the same network

  redis:
    image: redis:latest
    container_name: redis_service
    restart: always
    command: ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
    ports:
      - "6379:6379"
    networks:
      - ollama_network
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=strongpassword

  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama  # Use custom Dockerfile
    image: ollama/ollama
    container_name: ollama
    restart: always
    ports:
      - "11434:11434"  # Ollama API port
    volumes:
      - ollama_data:/root/.ollama  # Ollama persistent data volume
    networks:
      - ollama_network

  chromadb:
    image: ghcr.io/chroma-core/chroma:latest
    ports:
      - "8001:8001"
    volumes:
      - chroma_db:/chroma_db
    networks:
      - ollama_network

networks:
  ollama_network:
    driver: bridge

volumes:
  ollama_data:  # Named volume for Ollama's data
  chroma_db: # Named volume